name: 🏗️ Build

on:
  workflow_call:
    inputs:
      service:
        description: "Service folder to build"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 🔨 Build project (only for client)
        run: |
          if [ "${{ inputs.service }}" = "client" ]; then
            cd client && npm run build
          else
            echo "⚙️ No build step for server"
          fi
