name: 🚀 Docker Push

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image name"
        required: true
        type: string
      version:
        description: "Version tag from GitHub ref"
        required: true
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 🔐 Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 📤 Push Docker images (latest and versioned)
        run: |
          docker push ${{ inputs.image }}:latest
          docker push ${{ inputs.image }}:${{ inputs.version }}
