name: 📦 Install & Lint

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  install_lint:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 🗂️ Cache node_modules
        uses: actions/cache@v4
        with:
          path: ${{ inputs.path }}/node_modules
          key: ${{ runner.os }}-${{ inputs.path }}-${{ hashFiles(format('{0}/package-lock.json', inputs.path)) }}

      - name: 📦 Install Deps
        working-directory: ${{ inputs.path }}
        run: npm install --legacy-peer-deps

      - name: 🧹 Run Linter
        working-directory: ${{ inputs.path }}
        run: npm run lint
