name: 🧱 Build & Scan Server Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sa2avroo/testing-server

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v3

    - name: 🧰 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: 📦 Install Server Deps
      working-directory: ./server
      run: npm install --legacy-peer-deps

    - name: 🧹 Lint
      working-directory: ./server
      run: npm run lint || true

    - name: 🧪 Run Tests
      working-directory: ./server
      run: npm run test || true

    - name: 🏷️ Get Version from Tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: 🔐 Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🐳 Build Server Docker Image
      run: |
        docker build -t ${IMAGE_NAME}:latest ./server
        docker tag ${IMAGE_NAME}:latest ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}

    - name: 🔎 Trivy Scan (latest)
      uses: ./.github/workflows/trivy-scan.yml
      with:
        image: sa2avroo/testing-server:latest

    - name: 🔎 Trivy Scan (versioned)
      uses: ./.github/workflows/trivy-scan.yml
      with:
        image: sa2avroo/testing-server:${{ steps.get_version.outputs.VERSION }}

    - name: 🚀 Push Server Images
      run: |
        docker push ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:${{ steps.get_version.outputs.VERSION }}


# git tag v1.2.3
# git push origin v1.2.3 --tags