name: 🛡️ Trivy Scan

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Cache Trivy DB
      uses: actions/cache@v4
      with:
        path: ~/.cache/trivy
        key: trivy-db-${{ runner.os }}

    - name: 🛡️ Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo gpg --dearmor -o /usr/share/keyrings/trivy.gpg
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: 🔍 Trivy Scan ${{ inputs.image }}
      run: |
        echo "🔍 Scanning ${{ inputs.image }}..."
        trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress ${{ inputs.image }}
