name: 🧱 CI/CD Server

on:
  push:
    tags:
    - 'v*'

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tag.outputs.version }}
    steps:
    - id: tag
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  install_lint:
    needs: get_version
    uses: ./.github/workflows/common/install-lint.yml
    with:
      path: server

  build:
    needs: install_lint
    uses: ./.github/workflows/common/build-app.yml
    with:
      path: server

  docker_build:
    needs: build
    uses: ./.github/workflows/common/docker-build.yml
    with:
      path: server
      image: sa2avroo/testing-server
      version: ${{ needs.get_version.outputs.version }}

  trivy_latest:
    needs: docker_build
    uses: ./.github/workflows/common/trivy-scan.yml
    with:
      image: sa2avroo/testing-server:latest

  trivy_versioned:
    needs: docker_build
    uses: ./.github/workflows/common/trivy-scan.yml
    with:
      image: sa2avroo/testing-server:${{ needs.get_version.outputs.version }}

  push:
    needs: [ trivy_latest, trivy_versioned ]
    uses: ./.github/workflows/common/docker-push.yml
    with:
      image: sa2avroo/testing-server
      version: ${{ needs.get_version.outputs.version }}
